### PR TITLE
Updated info in intro section README.md

### PR DESCRIPTION
**Pull request by 05hiteshbansal**
added difference between Weak AI and Strong AI for better understanding the concept with proper difference

### CODE REVIEW

**Comment by 05hiteshbansal** [comment]
@videlalvaro please review my PR

**Comment by 05hiteshbansal** [comment]
@BethanyJep please review my PR

**Comment by 05hiteshbansal** [comment]
@BethanyJep please review my PR

**Comment by 05hiteshbansal** [comment]
@BethanyJep please review my PR

**Comment by 05hiteshbansal** [comment]
@carlotta94c please review my PR

**Comment by 05hiteshbansal** [comment]
@videlalvaro please review my PR

**Comment by 05hiteshbansal** [comment]
@BethanyJep please review and merge my PR

**Review by BethanyJep — APPROVED** [review]

**Pull request merged**
